server:
  port: 9023
logging:
  level:
    root: info
    com.springms: info
  file:
    max-history: 1000
    max-size: 50MB
    name: /home/username/permit.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:SSS} [%t] - [%p] [%c:%L] [%M] %m%n)'
    file: '%d{yyyy-MM-dd HH:mm:SSS} [%t] - [%p] [%c:%L] [%M] %m%n)'
permit:
  archives-room:
    room: redis
  verify-repository:
    repository: empty
